quarkus:
  rabbitmqclient:
    virtual-host: /
    username: guest
    password: guest
    client:
      port: 5672
  queue-policy:
    my-queue-name:
      retryable: true
      maxRetry: true
      dlq: true


