apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-deployment
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec:
      containers:
        - name: rabbitmq-image
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672




#
#
#volumes:
#  - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#  - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#  networks:
#    - rabbitmq_net